### ISSUE TITLE
 compile files('/Users/jemy/AndroidProjects/android-sdk/library/build/libs/library.jar')

### ISSUE THREAD

**Issue by BD1028994041** [qiniudemo/qiniu-lab-android#4]
这个 compile files('/Users/jemy/AndroidProjects/android-sdk/library/build/libs/library.jar')在哪里?

**Comment by jpsz01** [comment]
我也是醉了，这是官方demo吗？缺东少西的，态度不行啊
compile files('/Users/jemy/AndroidProjects/android-sdk/library/build/libs/library.jar')

**Comment by jemygraw** [comment]
已修复。
