### ISSUE TITLE
not have pldroid-player-2.1.3.jar'

### ISSUE THREAD

**Issue by zhuzhushang** [qiniudemo/qiniu-lab-android#6]
Error:Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Failed to transform file 'pldroid-player-2.1.3.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project5_as\qiniu-lab-android-master\QiniuLab\app\libs\pldroid-player-2.1.3.jar does not exist.

**Comment by jemygraw** [comment]
https://github.com/pili-engineering/PLDroidPlayer/tree/master/releases 可以从这里下载。

**Comment by jemygraw** [comment]
我顺便提交下吧。不过可以到上面的地址获取最新的jar。

**Comment by zhuzhushang** [comment]
在这里问你吧，我用的就是这个项目中的 “有key文件上传" 测试的. 相同的网络，手机可以上传成功，平板提示失败。有什么方法看问题出在哪里了吗？

**Comment by jemygraw** [comment]
我昨天回复你了，你的平板从日志看，就是解析域名得到的ip连不上，导致不断重试其他域名直到失败，所以调查下你的平板的联网情况。
